name: Thix_BP-Device-settings_01
label: Thix_BP-Device-settings_01
description: Sets recommend device settings for optimal security
type: panos
labels:
    collection: Thix BP
variables: []
snippets:
-   name: login-banner-321127
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <login-banner>USE OF THIS (Name of Company) SYSTEM, AUTHORIZED OR UNAUTHORIZED,
        CONSTITUTES CONSENT TO MONITORING OF THIS SYSTEM. UNAUTHORIZED USE
        MAY SUBJECT YOU TO CRIMINAL PROSECUTION. EVIDENCE OF UNAUTHORIZED USE
        COLLECTED DURING MONITORING MAY BE USED FOR ADMINISTRATIVE, CRIMINAL
        OR OTHER ADVERSE ACTION. USE OF THIS SYSTEM CONSTITUTES CONSENT TO
        MONITORING FOR THESE PURPOSES.</login-banner>
    cmd: set
-   name: minimum-length-632942
    xpath: /config/mgt-config/password-complexity
    element: <minimum-length>7</minimum-length>
    cmd: set
-   name: minimum-uppercase-letters-148772
    xpath: /config/mgt-config/password-complexity
    element: <minimum-uppercase-letters>1</minimum-uppercase-letters>
    cmd: set
-   name: minimum-lowercase-letters-756085
    xpath: /config/mgt-config/password-complexity
    element: <minimum-lowercase-letters>1</minimum-lowercase-letters>
    cmd: set
-   name: minimum-numeric-letters-925760
    xpath: /config/mgt-config/password-complexity
    element: <minimum-numeric-letters>1</minimum-numeric-letters>
    cmd: set
-   name: minimum-special-characters-13372
    xpath: /config/mgt-config/password-complexity
    element: <minimum-special-characters>1</minimum-special-characters>
    cmd: set
-   name: block-username-inclusion-382721
    xpath: /config/mgt-config/password-complexity
    element: <block-username-inclusion>yes</block-username-inclusion>
    cmd: set
-   name: new-password-differs-by-characters-385692
    xpath: /config/mgt-config/password-complexity
    element: <new-password-differs-by-characters>4</new-password-differs-by-characters>
    cmd: set
-   name: quota-settings-371281
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/setting/management
    element: |-
        <quota-settings>
                      <disk-quota>
                        <alarm>0.3</alarm>
                        <appstat>4</appstat>
                        <trsum>7</trsum>
                        <thsum>2</thsum>
                        <gtpsum>0.3</gtpsum>
                        <hourlygtpsum>0.3</hourlygtpsum>
                        <dailygtpsum>0.3</dailygtpsum>
                        <weeklygtpsum>0.3</weeklygtpsum>
                        <sctpsum>0</sctpsum>
                        <hourlysctpsum>0</hourlysctpsum>
                        <dailysctpsum>0</dailysctpsum>
                        <weeklysctpsum>0</weeklysctpsum>
                        <hipmatch>1</hipmatch>
                        <dlp-logs>0.3</dlp-logs>
                        <application-pcaps>1</application-pcaps>
                        <debug-filter-pcaps>1</debug-filter-pcaps>
                        <iptag>0.3</iptag>
                        <hip-reports>0.3</hip-reports>
                        <userid>0.3</userid>
                        <auth>0.3</auth>
                        <gtp>0.3</gtp>
                        <dailydesum>0.3</dailydesum>
                        <decryption>0.3</decryption>
                        <sctp>0</sctp>
                        <traffic>40</traffic>
                        <threat>22</threat>
                        <config>1</config>
                        <system>1</system>
                      </disk-quota>
                    </quota-settings>
    cmd: set
-   name: wildfire-376178
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/setting
    element: |-
        <wildfire>
                    <report-benign-file>yes</report-benign-file>
                    <report-grayware-file>yes</report-grayware-file>
                    <public-cloud-server>eu.wildfire.paloaltonetworks.com</public-cloud-server>
                  </wildfire>
    cmd: set
-   name: ctd-26176
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/setting
    element: |-
        <ctd>
                    <tcp-bypass-exceed-queue>no</tcp-bypass-exceed-queue>
                    <udp-bypass-exceed-queue>no</udp-bypass-exceed-queue>
                    <allow-http-range>no</allow-http-range>
                    <hold-client-request>yes</hold-client-request>
                  </ctd>
    cmd: set
-   name: ssl-decrypt-884349
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/setting
    element: |-
        <ssl-decrypt>
                    <crl>yes</crl>
                    <ocsp>yes</ocsp>
                  </ssl-decrypt>
    cmd: set
-   name: setting-865003
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
        <setting>
                    <ssl-decrypt>
                      <allow-forward-decrypted-content>yes</allow-forward-decrypted-content>
                    </ssl-decrypt>
                  </setting>
    cmd: set
